version: '3.3'

volumes:
  pathfinder-data:
  pathfinder-db:
  eve-db:

networks:
  pathfinder:

services:
  php:
    build:
      context: ./
    restart: always
    networks:
      - pathfinder
    volumes:
      - pathfinder-data:/var/www/html
      - ./pathfinder-config/environment.ini :/var/www/html/app/environment.ini
      - ./pathfinder-config/config.ini :/var/www/html/app/config.ini
      - ./pathfinder-config/pathfinder.ini :/var/www/html/app/pathfinder.ini
      - ./pathfinder-config/routes.ini :/var/www/html/app/routes.ini


  web:
    image: nginx:1.15.9-alpine
    restart: always
    networks:
      - pathfinder
    ports:
      - 8080:80
    volumes:
      - pathfinder-data:/var/www/html
      - ./pathfinder-nginx.conf :/etc/nginx/conf.d/default.conf

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: /run.sh --maxmemory 256mb
    networks:
      - pathfinder

  mariadb-pathfinder:
    image: mariadb:10.4
    restart: always
    networks:
      - pathfinder
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mariadb-pathfinder
      MYSQL_USER: mariadb-pathfinder
      MYSQL_PASSWORD: mariadb-pathfinder
    volumes:
      - pathfinder-db:/var/lib/mysql

  mariadb-eve:
    image: mariadb:10.4
    restart: always
    networks:
      - pathfinder
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mariadb-eve
      MYSQL_USER: mariadb-eve
      MYSQL_PASSWORD: mariadb-eve
    volumes:
      - eve-db:/var/lib/mysql