version: '3.3'

volumes:
  pathfinder-data:
  pathfinder-db:
  eve-db:

networks:
  default:
    external:
      name: nginx-proxy
  pathfinder:

services:
  pathfinder-app:
    build:
      context: ./pathfinder-app
    restart: always
    networks:
      - pathfinder
    volumes:
      - pathfinder-data:/var/www/html
      - ./pathfinder-config/environment.ini:/var/www/html/app/environment.ini
      - ./pathfinder-config/config.ini:/var/www/html/app/config.ini
      - ./pathfinder-config/pathfinder.ini:/var/www/html/app/pathfinder.ini
      - ./pathfinder-config/routes.ini:/var/www/html/app/routes.ini

  pathfinder-websockets:
    build:
      context: ./pathfinder-websockets
    restart: always
    networks:
      - pathfinder
    volumes:
      - pathfinder-data:/var/www/html

  web:
    image: nginx:1.15.9-alpine
    restart: always
    networks:
      - pathfinder
    expose:
      - 80
    environment:
      VIRTUAL_HOST: pathfinder.thefed.xyz
      LETSENCRYPT_HOST: pathfinder.thefed.xyz
      LETSENCRYPT_EMAIL: pathfinder@dont.ltd
    volumes:
      - pathfinder-data:/var/www/html
      - ./pathfinder-config/nginx-pathfinder.conf:/etc/nginx/conf.d/default.conf:ro
      - ./pathfinder-config/nginx.conf:/etc/nginx/nginx.conf:ro

  redis:
    image: bitnami/redis:latest
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    command: /run.sh --maxmemory 256mb --maxmemory-policy allkeys-lru
    networks:
      - pathfinder

  mariadb-pathfinder:
    image: mariadb:10.4
    restart: always
    networks:
      - pathfinder
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mariadb-pathfinder
      MYSQL_USER: mariadb-pathfinder
      MYSQL_PASSWORD: mariadb-pathfinder
    volumes:
      - pathfinder-db:/var/lib/mysql

  mariadb-eve:
    image: mariadb:10.4
    restart: always
    networks:
      - pathfinder
    command: ['--character-set-server=utf8', '--collation-server=utf8_general_ci']
    environment:
      MYSQL_ROOT_PASSWORD: changeme
      MYSQL_DATABASE: mariadb-eve
      MYSQL_USER: mariadb-eve
      MYSQL_PASSWORD: mariadb-eve
    volumes:
      - eve-db:/var/lib/mysql